# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'easy-verbs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'

  target 'easy-verbsTests' do
      inherit! :search_paths
      pod 'Firebase'
  end
  
end

